"""Agregado status_id y deleted_at al modelo TouristRating

Revision ID: 10442f908d8a
Revises: 0c5cb1ee1c54
Create Date: 2024-12-31 18:13:05.917450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10442f908d8a'
down_revision = '0c5cb1ee1c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'statuses', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
