"""Add app_version, platform, and last_login_at to users

Revision ID: 121c8443ec9b
Revises: 5224e25e42ce
Create Date: 2025-01-21 13:46:53.319917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121c8443ec9b'
down_revision = '5224e25e42ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('platform')
        batch_op.drop_column('app_version')

    # ### end Alembic commands ###
