"""Add status_id and deleted_at to ratings

Revision ID: 30367480c66c
Revises: 10442f908d8a
Create Date: 2025-01-02 06:59:05.290992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30367480c66c'
down_revision = '10442f908d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'statuses', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
