"""Add status_id to branch_ratings

Revision ID: 31ef330d72e6
Revises: 11dfa3c075e1
Create Date: 2024-12-31 09:44:31.696368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ef330d72e6'
down_revision = '11dfa3c075e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'statuses', ['status_id'], ['id'])

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('ratings_tourist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['tourist_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ratings_tourist_id_fkey', 'tourists', ['tourist_id'], ['user_id'])

    with op.batch_alter_table('branch_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
