"""Add discount_percentage to promotions

Revision ID: 3d40f1ea67a3
Revises: 
Create Date: 2024-07-30 20:17:51.978145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d40f1ea67a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('available_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['branch_id'], onupdate='CASCADE', ondelete='CASCADE')

    # Crear una sucursal predeterminada en la tabla branches si no existe
    op.execute("""
        INSERT INTO branches (branch_id, partner_id, name, description, address, latitude, longitude, status)
        VALUES (1, 1, 'Default Branch', 'This is a default branch for migrations', 'Default Address', 0.0, 0.0, 'active')
        ON CONFLICT (branch_id) DO NOTHING
    """)

    # Set a default value for existing rows
    op.execute('UPDATE promotions SET branch_id = 1 WHERE branch_id IS NULL')

    # Alter the column to not allow nulls
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('branch_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('available_quantity')
        batch_op.drop_column('branch_id')

    # Eliminar la sucursal predeterminada
    op.execute('DELETE FROM branches WHERE branch_id = 1')
    # ### end Alembic commands ###