"""empty message

Revision ID: 47f00e5610bf
Revises: 3d40f1ea67a3
Create Date: 2024-07-31 16:14:17.188793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f00e5610bf'
down_revision = '3d40f1ea67a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_tourist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tourists', ['user_id'], ['user_id'])
        batch_op.drop_column('tourist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tourist_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_tourist_id_fkey', 'tourists', ['tourist_id'], ['user_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
