"""Add app_versions table

Revision ID: 493eb4adb377
Revises: b4a179bf7db4
Create Date: 2025-01-14 08:52:13.529410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493eb4adb377'
down_revision = 'b4a179bf7db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
