"""Add app_type field to app_versions

Revision ID: 5224e25e42ce
Revises: 2cb661a8821b
Create Date: 2025-01-14 11:02:56.341695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5224e25e42ce'
down_revision = '2cb661a8821b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.drop_column('app_type')

    # ### end Alembic commands ###
