"""Add created_at column to Rating models

Revision ID: 52b520badf45
Revises: 342c5a8183a2
Create Date: 2024-08-09 07:30:38.881818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b520badf45'
down_revision = '342c5a8183a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tourist_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_ratings', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('branch_ratings', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
