"""Add image_url to branches

Revision ID: 720e3f266d4b
Revises: 47f00e5610bf
Create Date: 2024-08-01 11:58:16.419617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720e3f266d4b'
down_revision = '47f00e5610bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
