"""Add status_id to User

Revision ID: 82cacbafcc59
Revises: c71ba97d5dad
Create Date: 2024-08-16 16:23:56.873181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cacbafcc59'
down_revision = 'c71ba97d5dad'
branch_labels = None
depends_on = None


def upgrade():
    # Añadir columna status_id como nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(),  nullable=False, server_default='1'))

    # Asignar un valor por defecto a todos los registros existentes
    op.execute(
        "UPDATE users SET status_id = (SELECT id FROM statuses WHERE name = 'Activo' LIMIT 1) WHERE status_id IS NULL"
    )

    # Luego, hacer la columna no nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status_id', existing_type=sa.Integer(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
