"""Change fecha_nacimiento to string

Revision ID: af03a9b2599d
Revises: 
Create Date: 2024-07-15 19:21:04.441524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af03a9b2599d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
