"""Add prop quantity consumed a promotions

Revision ID: b3f5846ecae2
Revises: 92ec7e597502
Create Date: 2024-09-12 18:59:05.755958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f5846ecae2'
down_revision = '92ec7e597502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumed_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_column('consumed_quantity')

    # ### end Alembic commands ###
