"""Allow null in code column

Revision ID: c71ba97d5dad
Revises: a5637dd9a129
Create Date: 2024-08-12 11:18:45.713939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71ba97d5dad'
down_revision = 'a5637dd9a129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
        batch_op.drop_constraint('countries_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_unique_constraint('countries_code_key', ['code'])
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)

    # ### end Alembic commands ###
