"""Corrige la clave foránea para user_id en BranchRating

Revision ID: cb57ca7c9438
Revises: 69afa43c12c4
Create Date: 2025-01-03 07:38:01.825934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb57ca7c9438'
down_revision = '69afa43c12c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_ratings', schema=None) as batch_op:
        batch_op.drop_constraint('branch_ratings_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('branch_ratings_user_id_fkey', 'tourists', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
