"""Add image_url to users

Revision ID: e10170d11e99
Revises: 5321d5cbf3e3
Create Date: 2024-07-16 16:36:30.819401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e10170d11e99'
down_revision = '5321d5cbf3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))
        batch_op.drop_column('opciones_preferencias')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opciones_preferencias', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
