"""Recreate branch_ratings and tourist_ratings tables

Revision ID: e333661672d4
Revises: 
Create Date: 2024-08-06 10:58:41.390693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e333661672d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_unique_constraint('_tourist_point_tourist_uc', ['tourist_point_id', 'tourist_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('_tourist_point_tourist_uc', type_='unique')

    # ### end Alembic commands ###
