"""Renombrar tourist_id a user_id en branch_ratings

Revision ID: fea2448346c2
Revises: e333661672d4
Create Date: 2024-08-06 13:08:55.213568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea2448346c2'
down_revision = 'e333661672d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('branch_ratings_tourist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tourists', ['user_id'], ['user_id'])
        batch_op.drop_column('tourist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tourist_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('branch_ratings_tourist_id_fkey', 'tourists', ['tourist_id'], ['user_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
